# Generated by Django 3.2.9 on 2024-08-23 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoItems',
            new_name='ToDoItem',
        ),
    ]
